{% set version = "1.0.15" %}

package:
  name: libsodium
  version: {{ version }}

source:
  fn: libsodium-{{ version }}.tar.gz
  url: https://github.com/jedisct1/libsodium/releases/download/{{ version }}/libsodium-{{ version }}.tar.gz
  sha256: fb6a9e879a2f674592e4328c5d9f79f082405ee4bb05cb6e679b90afe9e178f4

build:
  skip: true  # [win and py>35]
  number: 0
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python  # [win]
    - msinttypes  # [win and py27]
  run:
    - vc 9  # [win and py27]
    - vc 14  # [win and py>=35]
  
test:
  commands:
    - test -f ${PREFIX}/lib/libsodium.a          # [unix]
    - test -f ${PREFIX}/lib/libsodium.dylib      # [osx]
    - test -f ${PREFIX}/lib/libsodium.so         # [linux]

about:
  home: https://github.com/jedisct1/libsodium
  license: ISC
  summary: A modern and easy-to-use crypto library.

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
