travis:
  secure:
    BINSTAR_TOKEN: vS49djoF+yrsosDeMUCJNJHDx37nKlJgQMtB2RlbRA0UACRfV/FIYi/f0faqay/NUZhOtnvHMt4uZZfHbDPF22detINI0H7GPcMvDWNCfNYlrAbs2SMbO/7Wn8H6dv1cA6EXtkd/Sxme99/ZT6SU5jTANJICPRpvpFyWnZspjI7MwY8AC7PrjJ0Kmy7MBVAdHM2XZkBx6otENHng211u0+CwPbdgCO8o8hraqkdciV2SMrBiiDbuiy4zwLuKZKfrbPtjeg1xZ+IzJ2YZKpv2Gn1ix/y0DHBcpMmXAjKWeCM0REYNveNODbbZf1deU27LVajkYvX89QBJCpH6inDpmRPI3ClHPhH6p/R3yGSpQnFFIS8w7xzRjdWadKg4U0jiBHBVJYFh6c+krxBqOQZFpQYseHYTYd9/PkPx/pcd0wrdcFl8yhQdeFuMVAdm664kjyAeVGpEyLZnDP209MgmgSoEeJiXk3ubo/Jjf1aVV77hFSXtkhDc8XcoYx0c6WYP8max7eOvMCJoOO/SQswTu2iaLBY43nbh0BR6rYHnJEF/J8ei6FCXT7cMqLdxnazUTtYj3VxWaoQKgXjQ5R2y3OehuZNzFoyCtAoZa7Zw0Kl/03mJYoxA3ZRce6ZScbNEvlUa5RMXkKVbFOz+r5GACKki0Ma9KHJQHL5Mp0/v3SI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
